### ISSUE TITLE
How to write polyglot keys?

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-guidelines#13]
Linked to #12, we should improve how we write polyglot keys. Actually, we found keys:
- capitalized
- lowercased
- with spaces / dashes / underscores
- with significant labels or not
- with structured terms order or not

This lack of consistency make maintenance and future contributions hard to make (even if contextualized phrases will simplifies it). I think we should establish a guideline for those keys. I recommend:
- lowercase only
- use underscore, no spaces allowed (more below)
- have structured order inside context, that name component, state, and element (i.e. `btn_validate_settings`)
- keep them sorted (a>z) so they can be found quickly and prevent overriding

***

Why use underscore?

IMHO, underscore should be preferable because:
- polyglot recommend and use them in their doc
- spaces are not very well-handled in JSON notation
- keys are… well… keys ; they're just ids, and add spaces may be confusing
- it's simpler to generate an underscored key from a name or a slug (which itself can easily be a key :wink:)

**Comment by jsilvestre** [comment]
The main issue with guidelines, it's when they exist, but they are not followed ;-) Thus I kinda disagree, they are pretty well followed.
http://cozy.io/hack/cookbooks/localization.html#localization-guidelines

* I have never seen a key with dashes or underscores
* they are all lowercased except a few that are basically the same word but with an uppercase

I agree some keys/content are weird, but most of the time it's because there is html inside the content and we had to play around it.

About improving the guidelines (I'm all for it)
* god please no "_" it just bloats the screen for nothing, none of your argument convince me (at all) -1 (but I believe separator is purely a matter of taste)
* Sorting a>z it can be a good idea, I tried to do it by logical sections, but that was utopic. a>z is completely rational so it sounds good
* contextualization +1

**Comment by m4dz** [comment]
> god please no "_" it just bloats the screen for nothing, none of your argument convince me (at all) -1 

Not sure, but if we use contexts, do `install wizard.next step` is really more readable than `install_wizard.next_step`?

> (but I believe separator is purely a matter of taste)

Totally :smile: 

> Sorting a>z it can be a good idea, I tried to do it by logical sections, but that was utopic. a>z is completely rational so it sounds good

Yep, I also prefer to sort by logical sections, but when the number of keys increase, it becomes totally unmaintainable. So a-z seems to be probably the more rational choice.

> contextualization +1

:metal:

**Comment by jsilvestre** [comment]
Yes with contextualization, it's better.

**Comment by frankrousseau** [comment]
Ok so to resume. What we'll do:

* Separators are spaces, other separators must be discarded
* The first word describes the context
* key names must be lowercased
* key names must be no longer than 30 chars or 4 words
* key names must be self-explicit
* key names must be in english

**Comment by m4dz** [comment]
> Separators are spaces, other separators must be discarded

Dunno, because I'm now not sure about @jsilvestre last comment. @jsilvestre, what did you mean: spaces or underscores, which one is better if we use contexts?

> The first word describes the context
If it's relevant. Some terms can be use generically. Or we force the context, and we create at least a `general` context ? Or the app name ? Something like `contact.validate` and `contact.vcard.name` ?

**Comment by jsilvestre** [comment]
If we use context, it's better to use "_" as a separator, cf your example.

**Comment by frankrousseau** [comment]
No, we should keep it simple: space only and explicit names. If you need more than one word to describe the context, use the first two words to describe the context. The 4 words limit can be extended, if you think it's too short.

**Comment by frankrousseau** [comment]
The goal is to make developers think the less possible. Bringing another comparator will add ambiguity.
