### ISSUE TITLE
fast return

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-guidelines#9]
# Problem

```coffee
myFunction = (callback) ->
    doStuff1 (err ) ->
        return callback err if err
        doStuff2 (err, result) ->
            return callback err if err
            callback null, result
```
vs
```coffee
myFunction = (callback) ->
    doStuff1 (err ) ->
        if err
            callback err
        else
            doStuff2 (err, result) ->
                if err
                    callback err
                else
                    callback null, result
```

I prefer and always use the return fast approach. @frankrousseau prefer the if/else approach and we have both ~50% in our codebase

# Returns
- GOOD : smaller / cleanear amha
- GOOD : more readble amha : this line means if there is an error, pass it above and dont think about it in the rest of the function
- BAD : easy to forget (coffee-jshint to the rescue)

# if/else
- GOOD : more explicit, expose complexity (force smaller functions)
- GOOD : easier to expand to handle more error case [1]
- BAD : amha, need some braintick to see if we handle err, transform it, ignore it

```coffee
# [1]
doStuff (err, body) ->
    if err and err.code is 'YOLO'
        callback new Error 'yolo'
    else if body.error is 'not_found'
        callback NotFoundError 'that stuff'
    else if err
        callback err
   else
         callback null, body.stuff
```

**Comment by frankrousseau** [comment]
Three additions: 
* First case is probably not optimized for interpreters (because method termination location is not obvious). 
* First case often leads to put returns in the middle of the method.
* First case looks to be the trend (newcomers to the problematic only sees direct advantages and don't see side effects).

**Comment by aenario** [comment]
Optimization : these two solutions are equivalent at least in node/v8 (https://gist.github.com/aenario/551724be0de2c9600645)

This is purely a style choice. 

------------

"First case often leads to put returns in the middle of the method which makes it hard to debug."

Sorry, I dont see what you mean.

-----------

"First case looks to be the trend (newcomers to the problematic only sees direct advantages and don't see side effects)."

Most established projects use them too.

https://github.com/npm/npm/blob/master/lib/install.js#L37
https://github.com/joyent/node/blob/885f72105bf0b18007100550f131c85ca56536e0/lib/_debugger.js#L281
https://github.com/strongloop/express/blob/9434ad39e114ea810859cd9c6fef624d4acfbe18/lib/response.js#L398

**Comment by aenario** [comment]
Sorry if i appears vindicative, if we decide as a team to use if/else, i will gladly follow along. 
I just want us to decide for actual reason like "it prevents us from making too big functions"

**Comment by frankrousseau** [comment]
I mean that most of the time people consider they can break the function anywhere with that trick. That leads to unexpected returns in the middle of the function (not only to handle error case).

**Comment by jsilvestre** [comment]
My rather objective argument is: throwing error should be the only thing that breaks the flow of execution.

**Comment by jsilvestre** [comment]
My pragmatic self would say: it's okay to return fast ONLY IF IT'S EXLACTLY `return callback err if err?`

**Comment by m4dz** [comment]
Fast return isn't just a trending pattern. It implicitely include a notion of error handling and, I agree with Joseph on this point, _should_ be used only in this case. A typical case I can see is something like this in rendering method:

```coffee
showElement:
    if @$el.is ':empty' then return

    # the stuff I need to do if rendering previously occurs...
```

or

```coffee
doStuff: (callback) ->
    # do my stuff...
    
    # ensure callback exists and is a function
    unless callback? and typeof callback is 'function' then return
    callback()
```

that is a typical case in plugins that can accept external callbacks and is a more readable way to write it rather than enclosing call in a condition.

Another argument is that it keep the code more concise and prevent a nested pyramid of doom, which is especially useful when we want to wrap code at 80 chars and use indents at 4 spaces (especially in DOM manipulations that can contains long classNames :wink:).

**Comment by jsilvestre** [comment]
I disagree with your first example, this is not error handling. If it was, since it's a synchronous function, it would be `throw new Error('something')`. I realized yesterday that I would use it only in async functions, where I would have used "throw new Error()" in synchronous function, and that makes sense (at least to me^^). Also, I tend to do it only if there are nested conditions afterwards (to save one level), if it's just:

```coffeescript
doStuff: (status) ->
    if status >= 400
        console.log "an error occurred"
       # do something
```
No need to write:
```coffeescript
doStuff: (status) ->
    return if status < 400
    console.log "an error occurred"
    # do something
```

Just to be sure you understand me well, when I speak about errors, this is what I mean: an error is unexpected, the case your list is empty is not unexpected (if that's the case, it should throw before the render anyway).

**Comment by frankrousseau** [comment]
I agree with Joseph, it should not be used it except for the `return callback err if err`. That's a very common case in Node.js and handle it that way, seems ok. Not having two level of indentation each time an async call is made sounds normal. 

For all other cases, it leads to unreadable "branching". A flow of execution is a kind of tree. Breaking the indentation breaks the visual tree.  Which is wrong because it makes the code analysis harder.

Too much nested levels is a sign that it's time to split the function in smaller pieces.

**Comment by jsilvestre** [comment]
One more thing, I wrote code this afternoon and I realized that I find "return" more readable on one-liner. Every other case look weird, e.g.
```coffeescript
        if err?
            log.error err
            return callback err
       # do your thing
       callback()
```
So if the line doesn't start by "return", I'd say let's do a proper condition. If it starts by return (and it's an error case), it's fine.
This is purely subjective, though.

**Comment by frankrousseau** [comment]
Ok so I put this in the guidelines. Feel free to discuss it via a PR:

Return Shortcuts

Return shortcuts should not be used by default. They can be used to avoid branching that have very few meaning. The most known case where it occurs:

```coffeescript
myfunc (err) ->
    return callback err if err
```

**Comment by frankrousseau** [comment]
I close the issue. As said above, if you have any comments open a PR about the subject.
